### ISSUE TITLE
接入后 有经纬度但是地址属性那里是未知？

### ISSUE THREAD

**Issue by MagicStarTrace** [ryanh7/ha-traccar#3]
![image](https://github.com/ryanh7/ha-traccar/assets/15685376/4b08fc85-f9e7-4be3-9a0b-04e79891e7a1)

Home Assistant 版本 2023.8.3

我看经纬度是有的，但是接到hass后地址属性那里是未知

![image](https://github.com/ryanh7/ha-traccar/assets/15685376/abcec08b-24d2-4163-b16e-b8214ff532a7)

traccar 使用的是bg6rsh/traccar-amap:5.8 的镜像

**Comment by ryanh7** [comment]
需在"http://traccar服务器/api/positions"中正确返回address

**Comment by MagicStarTrace** [comment]
> 需在"[http://traccar服务器/api/positions"中正确返回address](http://traccar%E6%9C%8D%E5%8A%A1%E5%99%A8/api/positions%22%E4%B8%AD%E6%AD%A3%E7%A1%AE%E8%BF%94%E5%9B%9Eaddress)

![image](https://github.com/ryanh7/ha-traccar/assets/15685376/1114c703-43af-4e8a-9a0c-68fcb697dcd1)

版本不一样？我的好像没在这里 需要由经纬达转换下？
